"""empty message

Revision ID: 29be2d29cd0d
Revises: 
Create Date: 2018-08-12 00:36:30.477403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29be2d29cd0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recognize', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recognize', 'score')
    # ### end Alembic commands ###
